name: Publish and Sign Snapshot Image
description: Publishes and signs a snapshot image using Dagger.

inputs:
  REGISTRY_ADDRESS:
    description: 'Registry address (e.g., ghcr.io)'
    required: true
  REGISTRY_USERNAME:
    description: 'Registry username (e.g., nucleocode)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Dagger Version
      uses: sagikazarmark/dagger-version-action@v0.0.1

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Debug OIDC Environment
      shell: bash
      run: |
        echo $REGISTRY_PASSWORD
        echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
        echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN present: $([[ -n \"$ACTIONS_ID_TOKEN_REQUEST_TOKEN\" ]] && echo yes || echo no)"
        cosign version

    - name: Publish and Sign Image
      uses: dagger/dagger-for-github@v7
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REGISTRY_ADDRESS: ${{ inputs.REGISTRY_ADDRESS }}
        REGISTRY_USERNAME: ${{ inputs.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ inputs.REGISTRY_PASSWORD }}
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
      with:
        version: ${{ steps.dagger_version.outputs.version }}
        verb: call
        args: "publish-and-sign-image --source=. --registry-address=${{ inputs.REGISTRY_ADDRESS }} --registry-username=${{ inputs.REGISTRY_USERNAME }} --registry-password=env://REGISTRY_PASSWORD --github-token=env://GITHUB_TOKEN --actions-idtoken-request-url=env://ACTIONS_ID_TOKEN_REQUEST_URL --actions-idtoken-request-token=env://ACTIONS_ID_TOKEN_REQUEST_TOKEN"
