name: Publish and Sign Snapshot Image
description: Publishes and signs a snapshot image using Dagger.

inputs:
  IMAGE_TAGS:
    description: 'Tags for the image, e.g. "latest, v1.0.0"'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  REGISTRY_PASSWORD:
    description: 'Registry password'
    required: true
  REGISTRY_ADDRESS:
    description: 'Registry address'
    required: true
  REGISTRY_USERNAME:
    description: 'Registry username'
    required: true
  BUILD_DIR:
    description: 'Build Directory path'
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Dagger Version
      uses: sagikazarmark/dagger-version-action@v0.0.1

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Get Build Artifact
      if: ${{ inputs.BUILD_DIR != '' }}
      uses: actions/download-artifact@v4
      with:
        name: build-dir
        path: ${{ inputs.BUILD_DIR }}

    - name: Check Env Variables
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: cosign env
 

    # - name: Build optional build-dir arg
    #   shell: bash
    #   run: |
    #     if [ -n "${{ inputs.BUILD_DIR }}" ]; then
    #       echo "DAGGER_BUILD_DIR_ARG=--build-dir=${{ inputs.BUILD_DIR }}" >> $GITHUB_ENV
    #     else
    #       echo "DAGGER_BUILD_DIR_ARG=" >> $GITHUB_ENV
    #     fi


    # - name: Dump args for debugging
    #   shell: bash
    #   run: |
    #     echo "BUILD_DIR input: '${{ inputs.BUILD_DIR }}'"
    #     echo "DAGGER_BUILD_DIR_ARG: '$DAGGER_BUILD_DIR_ARG'"
    #     env | grep DAGGER_BUILD_DIR_ARG

    - name: Publish and Sign Snapshot Image
      uses: dagger/dagger-for-github@v7
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REGISTRY_ADDRESS: ${{ inputs.REGISTRY_ADDRESS }}
        REGISTRY_USERNAME: ${{ inputs.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ inputs.REGISTRY_PASSWORD }}
        IMAGE_TAGS: ${{ inputs.IMAGE_TAGS }}
      with:
        version: ${{ steps.dagger_version.outputs.version }}
        verb: call
        args: >
          publish-image-and-sign 
          --progress=plain 
          --registry=${{ env.REGISTRY_ADDRESS }} 
          --registry-username=${{ env.REGISTRY_USERNAME }}
          --registry-password=env://REGISTRY_PASSWORD
          --image-tags=${{ env.IMAGE_TAGS }}
          --github-token=env://GITHUB_TOKEN
          --actions-id-token-request-url=env://ACTIONS_ID_TOKEN_REQUEST_URL
          --actions-id-token-request-token=env://ACTIONS_ID_TOKEN_REQUEST_TOKEN
